import type { CourseGuide } from './types';

export const portrushGuide: CourseGuide = {
  slug: 'portrush',
  name: 'Royal Portrush',
  nameLines: ['Royal', 'Portrush'],
  subtitle: 'Dunluce Links · Portrush, Co. Antrim',
  tees: 'White tees',
  par: 72,
  yards: 6729,
  architects: 'Harry Colt 1929 · Martin Ebert 2017 · The Open 1951, 2019, 2025',
  strapline: "Joe's notes where he had them; the club's course guide where he didn't",
  cover: '/guides/portrush/cover.jpg',
  rulesTitle: "Joe's Rules, Portrush edition",
  rulesIntro: 'Less blind than County Down, more going on at the greens. Read once, then trust it.',
  rules: [
    {
      title: 'Driver down the center, almost everywhere.',
      body: "Joe's read on Portrush: most of the course is driver. The layups are 1 (short of the left bunker), 5 if you aren't going for it, and 8 or 9 if the wind says so.",
    },
    {
      title: 'What you see is what you get.',
      body: 'Far less blind than County Down. Nothing here should shock you. Stone markers and caddie lines matter less; the wind matters more.',
    },
    {
      title: "Fly it on. You can't run it up.",
      body: 'False fronts on 1, 6, 8, 11, 12 and 14, steep runoffs on 9, 15 and 16. Take enough club to carry the front of the green and stop it.',
    },
    {
      title: 'Get it on the green. No hero chips.',
      body: 'Short-sided on a steep runoff, the mistake is trying to hit it to two feet and leaving it at your feet with the same shot again. Ten feet past the hole is fine.',
    },
    {
      title: 'Putt from off the green.',
      body: 'The fringe is smoother than at home and the ball rolls true. The pros putted from off these greens a lot, including the ones with great short games. Keep the wedges in the bag, use them less.',
    },
    {
      title: 'Wind is the biggest thing. Overwhelmingly.',
      body: "Into it, dispersion widens: take more club and swing easier, less spin. Downwind, dispersion tightens: send it. Check Windfinder's Superforecast 48 hours out and write the wind on each hole page.",
    },
    {
      title: 'Prevailing wind is westerly.',
      body: 'Roughly, 1 to 4 and 16 to 18 play into or down it; 5 through 15 play across it. Crosswind holes are the ones that eat fairways. Confirm with your caddie on the first tee.',
    },
    {
      title: 'Keep penalty shots off the card.',
      body: "OB on 1 (both sides), 2, 4 and 18, and three yards behind the 5th green. Angles are worth nothing; Scottie isn't playing angles and neither are you. It's greener and less baked than Carnoustie, so runout matters less than wind.",
    },
  ],
  holes: [
    {
      n: 1, par: 4, yards: 382, si: 11, tags: ['3W / IRON', 'OB BOTH SIDES'], source: 'guide',
      offTheTee: '3W or iron, short of the left bunker.',
      sections: [
        { label: 'TEE', text: "Internal out of bounds down both sides. The head pro's play is a 3-wood or long iron laid up short of the bunker on the left, then a mid-iron in. Rory made 8 here in 2019 going left." },
        { label: 'LINE', text: 'Center of the fairway. Left is the bunker and OB beyond it; right is OB.' },
        { label: 'BUNKERS', text: '248 left, 229 right.' },
        { label: 'IN', text: "Uphill to an elevated green with a big false front. Fly it all the way on. Favor the right half; there's a deep bunker left and heavy rough behind it. The green cambers from the right." },
        { label: 'JOE', joe: true, text: 'Really big false front short of this green. One to have in your notes.' },
        { label: 'NOTE', text: 'The most demanding opening tee shot of the trip. Bogey here is not a disaster; a re-tee is.' },
      ],
    },
    {
      n: 2, par: 5, yards: 536, si: 5, tags: ['DRIVER / 3W'], source: 'guide',
      offTheTee: 'Driver or 3W, left-center.',
      sections: [
        { label: 'TEE', text: "OB down the right, thick rough left, and four bunkers in the driving zone. Driver if you're driving it well; a 3-wood takes most of the bunkers out of play and keeps the OB off your card." },
        { label: 'LINE', text: 'Left-center, away from the road. The pros hug the left to reach in two; you only need a buffer from the OB.' },
        { label: 'BUNKERS', text: '241 and 263 down the right side.' },
        { label: 'IN', text: 'Three cross bunkers sit about 60 yards short of the green, right on the line, with pot bunkers about 30 short. Going for it means flying all of them. Laying up means stopping short of the crosses with a full wedge left.' },
        { label: 'NOTE', text: "Giant's Grave. Early birdie chance for the pros, a par 5 in three good shots for you." },
      ],
    },
    {
      n: 3, par: 3, yards: 155, si: 17, tags: ['CENTER'], source: 'guide',
      offTheTee: 'Middle of the green.',
      sections: [
        { label: 'CLUB', text: '155 to an elevated green that runs firm.' },
        { label: 'LINE', text: 'Middle of the green whatever the pin. The green slopes right to left, so a little fade holds it best.' },
        { label: 'WATCH', text: 'Straightforward until you miss. Slopes and swales all around bring bogey in fast, and the elevated surface runs away from you.' },
        { label: 'BUNKERS', text: '130 to the one bunker, front left of the green.' },
        { label: 'NOTE', text: 'Islay. Hit the middle, two putts, walk.' },
      ],
    },
    {
      n: 4, par: 4, yards: 455, si: 1, tags: ['DRIVER'], source: 'joe',
      offTheTee: 'Driver, center, hair left.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: "Driver. Joe: you can't take the trouble out of play on this hole. OB down the right, bunkers on the left. Aim down the center with a slight lean to left-center for a buffer from the OB. If you end up in a left bunker, you end up in a left bunker." },
        { label: 'LINE', joe: true, text: 'Center, a hair left.' },
        { label: 'BUNKERS', text: '221 and 240 down the left.' },
        { label: 'WATCH', joe: true, text: "Stroke index 1 and Joe's pick for the hardest hole on the course. Step up and hit a really good drive." },
        { label: 'IN', text: 'The green sits in the sandhills and all the trouble on the second shot is at the front. Aim for the back portion and let the contours bring it back.' },
        { label: 'NOTE', joe: true, text: "Fred Daly's. The course starts here, per Joe." },
      ],
    },
    {
      n: 5, par: 4, yards: 375, si: 15, tags: ['240 TO 250 / GO', 'OB BEHIND'], source: 'joe',
      offTheTee: '240 to 250 at the corner, or go.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: "Two plays. Hit something 240 to 250 to the corner and leave a full shot, or, if it's downwind and you drive it well, go for it. That was the popular play at the Opens; on the day they set it up most drivable in 2025 nearly everyone did it. Joe likes the aggressive play if it's you." },
        { label: 'LINE', joe: true, text: 'Hard dogleg right. Don\'t lay way short and way left: the second from there is way uphill to an angled green.' },
        { label: 'WATCH', joe: true, text: 'Out of bounds is about three yards behind the green. Never go long. Bunkers right and left of the green; a steep step a third of the way up, then it runs downhill toward the back.' },
        { label: 'IN', text: 'Front to middle of the green, short of the flag rather than past it.' },
        { label: 'NOTE', joe: true, text: "White Rocks. Joe's pick for best hole on the course and the photo hole: Dunluce Castle and the Causeway coast off the green." },
      ],
    },
    {
      n: 6, par: 3, yards: 185, si: 7, tags: ['ALL CARRY'], source: 'guide',
      offTheTee: 'Fly it on. Middle.',
      sections: [
        { label: 'CLUB', text: "185 from the tee by the beach. You have to fly it on: there's a false front and no running it up." },
        { label: 'LINE', text: "Middle of the green. It's big, but there are swales on both sides." },
        { label: 'WATCH', text: "The false front. Short rolls back off the green. There's a small upper section at the back that tapers in; ignore it and hit the middle." },
        { label: 'NOTE', text: "Harry Colt's. He wanted his name on this one after finishing the course. Take enough club." },
      ],
    },
    {
      n: 7, par: 5, yards: 552, si: 3, tags: ['DRIVER'], source: 'guide',
      offTheTee: 'Driver, away from Big Nellie.',
      sections: [
        { label: 'TEE', text: "Driver. It looks tighter than it is: the huge bunker on the right is Big Nellie, there's another bunker left, and the landing area feels narrow with driver in hand. Rory aims up the left and cuts it." },
        { label: 'LINE', text: 'Center to left-center, away from Big Nellie.' },
        { label: 'WATCH', text: 'The approach plays uphill through a narrow corridor pinched by banks and bunkers left and right. The drop-off left of the green is severe.' },
        { label: 'IN', text: 'Three shots. Lay up to a full wedge short of the corridor, then hit the middle. The green feeds to the center if you\'re on line and repels anything off line.' },
        { label: 'NOTE', text: 'Curran Point. The longest hole for you at 552 and the hardest of the par 5s at the Open. Par is a good score.' },
      ],
    },
    {
      n: 8, par: 4, yards: 414, si: 13, tags: ['DRIVER / 3W'], source: 'guide',
      offTheTee: '3W short of the right bunkers, or driver.',
      sections: [
        { label: 'TEE', text: "Wind decides it. Dogleg left with bunkers on the right at the corner: lay back short of them with a 3-wood or long iron, or take driver and carry them if it's helping. Rory's split is the same." },
        { label: 'LINE', text: 'Center. Short of the bunkers unless you know you can carry them.' },
        { label: 'WATCH', text: 'Left is dead. Anything short of the green catches a false front and rolls into a hollow that sees a lot of traffic.' },
        { label: 'BUNKERS', text: 'Two on the right at the landing area. 294 to the bunker short left of the green.' },
        { label: 'IN', text: 'Take enough club to carry the false front. Narrow entrance; a good drive leaves a wedge.' },
        { label: 'NOTE', text: 'Dunluce. New in 2019 and one of the cleverest holes on the course.' },
      ],
    },
    {
      n: 9, par: 4, yards: 418, si: 9, tags: ['DRIVER / 3W'], source: 'joe',
      offTheTee: 'Driver or 3W short of 249.',
      sections: [
        { label: 'TEE', text: "Driver or 3-wood, short of the bunkers on the right. That was Shane Lowry's play in 2019. Left is a no-go: a big bank blocks your view of the green from over there." },
        { label: 'LINE', text: 'Center.' },
        { label: 'BUNKERS', text: '249 to the bunker on the right.' },
        { label: 'IN', text: "Uphill second over a pair of cross bunkers to an angled green. There's a buffer at the back that rolls a slightly long shot back." },
        { label: 'JOE', joe: true, text: 'Pretty steep runoff right of the green. Not a terrible place to be, but severe. Have it in your notes.' },
        { label: 'NOTE', text: "Darren Clarke's, one of his favorite holes. The pro calls 9, 10 and 11 the tough middle of the course." },
      ],
    },
    {
      n: 10, par: 4, yards: 373, si: 12, tags: ['DRIVER'], source: 'guide',
      offTheTee: 'Driver, slightly left of center.',
      sections: [
        { label: 'TEE', text: 'Driver. No bunkers on the hole; the humps, hollows and sandhills down the right are the Himalayas.' },
        { label: 'LINE', text: 'Slightly left of center. A good drive clears the shoulder in the fairway and gives you a view of the green.' },
        { label: 'WATCH', text: 'Long, narrow green with pronounced contours the farther back you go.' },
        { label: 'IN', text: 'Center of the green, front half.' },
        { label: 'NOTE', text: 'Himalayas. Par is a good score here, per the head pro.' },
      ],
    },
    {
      n: 11, par: 5, yards: 472, si: 8, tags: ['DRIVER', 'FALSE FRONT'], source: 'joe',
      offTheTee: 'Driver, center. Carry the false front.',
      sections: [
        { label: 'TEE', text: 'Driver. Probably the most demanding tee shot on the course: thick rough and lots of little sandhills and humps, with the fairway bending right around the dunes.' },
        { label: 'LINE', text: 'Center.' },
        { label: 'WATCH', text: 'A big sand blowout right of the landing area. The green is small and perched, with a false front that can send a ball 30 or 40 yards back down the fairway into a valley.' },
        { label: 'IN', text: 'Carry the front or lay up to a full shot and carry it then. Short is the one miss that costs you.' },
        { label: 'JOE', joe: true, text: 'Pretty big runoff here. Note it.' },
        { label: 'NOTE', text: "P.G. Stevenson's. Par 5 on the club card (the app calls it a 4). Toughest hole at the 2019 Open. Three shots is fine." },
      ],
    },
    {
      n: 12, par: 5, yards: 499, si: 4, tags: ['DRIVER', 'SCORING'], source: 'joe',
      offTheTee: 'Driver, left-center. Go in two.',
      sections: [
        { label: 'TEE', text: 'Driver from an elevated tee. The fairway slopes toward three bunkers on the right; the rough has been grown up on the left.' },
        { label: 'LINE', text: 'Left-center and let the slope feed it back.' },
        { label: 'BUNKERS', text: '222, 254 and 286 down the right.' },
        { label: 'IN', joe: true, text: 'Reachable in two after a good drive. Big false front: hit it far enough to clear it. The green falls away to the right toward a swale.' },
        { label: 'JOE', joe: true, text: "There's a little creek short right of the green that you can't see. Don't hit what looks like a good shot and get surprised. Water short right." },
        { label: 'NOTE', text: 'Dhu Varren. Easiest hole at the 2019 Open and your best scoring chance.' },
      ],
    },
    {
      n: 13, par: 3, yards: 165, si: 18, tags: ['CENTER'], source: 'guide',
      offTheTee: 'Middle. Less club downwind.',
      sections: [
        { label: 'CLUB', text: '165 from an elevated tee. The drop makes the green look smaller than it is.' },
        { label: 'LINE', text: 'Middle of the green.' },
        { label: 'WATCH', text: 'Five bunkers around the green. The green slopes front to back; downwind, balls run through. Take less club when it\'s helping.' },
        { label: 'BUNKERS', text: '148 and 162 left, 163 right.' },
        { label: 'NOTE', text: 'Feather Bed. Easiest by index, and Grillo aced it in 2019. Par and move on.' },
      ],
    },
    {
      n: 14, par: 4, yards: 386, si: 2, tags: ['DRIVER'], source: 'guide',
      offTheTee: 'Driver, center.',
      sections: [
        { label: 'TEE', text: 'Driver. This hole is all about the second shot.' },
        { label: 'LINE', text: 'Center.' },
        { label: 'BUNKERS', text: '240 left, 232 right at the landing area.' },
        { label: 'WATCH', text: 'You usually get a hanging lie, ball above your feet, which pulls a right-hander left, and left is where the horrible greenside bunker is. Tabletop green with a false front. Nothing good over the back; the right side falls to a shelf that stays up.' },
        { label: 'IN', text: 'Right-center of the green, enough club to carry the front, not enough to go long.' },
        { label: 'NOTE', text: 'Causeway. Stroke index 2. Par wins holes.' },
      ],
    },
    {
      n: 15, par: 4, yards: 370, si: 14, tags: ['DRIVER', 'SEMI-BLIND'], source: 'guide',
      offTheTee: 'Driver over the left sandhills.',
      sections: [
        { label: 'TEE', text: "Driver. Rory's favorite hole and one of the more generous fairways on the course. The drive is semi-blind over the sandhills on the left, aimed away from the three bunkers on the right." },
        { label: 'LINE', text: 'Left-center over the sandhills. Caddie sets the line.' },
        { label: 'BUNKERS', text: '209 and 248 down the right.' },
        { label: 'IN', text: 'This is where the hole bites. Downhill to a small target with steep slopes front and right and bunkers left. Get the number right and hit the middle.' },
        { label: 'NOTE', text: 'Skerries. A good drive makes it a birdie look; a careless second makes it a 5.' },
      ],
    },
    {
      n: 16, par: 3, yards: 206, si: 6, tags: ['HARDEST SHOT'], source: 'joe',
      offTheTee: 'Back-left of the green.', teeIsJoe: true,
      sections: [
        { label: 'CLUB', joe: true, text: "206 over the chasm. Into the wind it's a fairway wood; downwind a lot less. Joe: probably the hardest shot you'll hit all day." },
        { label: 'LINE', joe: true, text: 'Left-center. Aim away from the right and give yourself a buffer. The safe play is the back-left portion of the green.' },
        { label: 'WATCH', joe: true, text: "Anything short or right is completely dead: a 50 to 60 foot drop into thick stuff. Left doesn't leave an easy chip, but it's alive. Bobby Locke's Hollow is just left of the green; members putt from there and walk off with 3 all the time." },
        { label: 'NOTE', joe: true, text: 'Calamity Corner. Some say the best hole on the course. Three here is a win every time, for the pros too.' },
      ],
    },
    {
      n: 17, par: 4, yards: 360, si: 16, tags: ['DRIVER', 'DOWNHILL'], source: 'joe',
      offTheTee: 'Driver, right-center.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: 'Joe would be aggressive: pound driver and let it bounce down the hill. The hole drops away hard at about 270, blind from the tee. Some guys will hit 3-wood to stay on top; Joe has no issue with driver and getting it 40 to 50 yards from the green on the right day. Talk it through with your caddie.' },
        { label: 'LINE', text: 'Center to right-center. A bunker sits at the base of the hill on the left; anything left of center can trickle down into it and leave an awkward 60-yard bunker shot.' },
        { label: 'BUNKERS', text: '294 to the bunker at the bottom of the hill, left.' },
        { label: 'IN', text: 'Short pitch. Middle of the green.' },
        { label: 'NOTE', text: 'Purgatory. The fun one. The pros mostly took a crack at it.' },
      ],
    },
    {
      n: 18, par: 4, yards: 426, si: 10, tags: ['DRIVER', 'OB LEFT'], source: 'joe',
      offTheTee: 'Driver, center.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: 'Driver, straight down the middle. You could hit 3-wood; Joe would still hit driver. OB down the left, bunkers to catch shots on the right. Elevated tee.' },
        { label: 'LINE', joe: true, text: "Center. The pros favor the left near the OB for the angle in; Joe says the angle isn't worth it." },
        { label: 'BUNKERS', text: '247 on the left edge of the fairway.' },
        { label: 'IN', text: 'One deep bunker guards the right of the green; anything a little left gets swept into a big hollow. Middle of the green.' },
        { label: 'NOTE', text: "Babington's. Finish under the clubhouse. Max Faulkner won the 1951 Open with a slice out of the barbed wire here; you don't need to." },
      ],
    },
  ],
  quickLook: [
    { title: 'Out of bounds: 1, 2, 4, 5, 18', body: '1 has it on both sides. 2 and 4 right. 18 left. 5 is three yards behind the green, so never go long there.' },
    { title: 'Lay-ups: 1, and 5, 8, 9 depending on wind', body: "1 stops short of the left bunker at 248. 5 is 240 to 250 unless you're going for it downwind. 8 lays short of the right bunkers unless it's helping. 9 stays short of the bunker at 249." },
    { title: 'False fronts: 1, 6, 8, 11, 12, 14', body: "Enough club to carry the front, every time. 11's can send a ball 40 yards back into a valley." },
    { title: 'Runoffs: 7 left, 9 right, 15 front and right, 16 short and right', body: "16 is the one that's dead. The others are up-and-down territory if you putt or bump it up instead of getting cute." },
    { title: 'Hidden water: 12', joe: true, body: "A small creek short right of the green that you won't see from the fairway. Joe's note." },
    { title: 'Scoring chances: 2, 12, 5, 17, 13', body: 'Two par 5s, two short par 4s where the wind can let you go for it, and the easiest par 3.' },
    { title: 'Toughest by index: 4, 14, 7, 12', body: 'Par on any of these is a point. 16 by feel.' },
    { title: 'Photos: 5, 6 tee, 16', body: '5 green looks along the coast to Dunluce Castle. The 6th tee sits by the beach. 16 is Calamity.' },
  ],
  closing: ['Fly it on.', 'Putt from the fringe.', 'Play the wind.'],
  closingSub: 'What you see is what you get. Keep the penalties off the card.',
};
