import type { CourseGuide } from './types';

export const rcdGuide: CourseGuide = {
  slug: 'rcd',
  name: 'Royal County Down',
  nameLines: ['Royal', 'County Down'],
  subtitle: 'Championship Links · Newcastle, Co. Down',
  tees: 'Yellow tees',
  par: 71,
  yards: 6641,
  architects: 'Old Tom Morris 1889 · Combe · Vardon · Harry Colt 1926',
  strapline: 'Strategy notes condensed from the call with Joe',
  cover: '/guides/rcd/cover.jpg',
  rulesTitle: "Joe's Rules",
  rulesIntro: 'Same answer on most tees. Read this once, then trust it.',
  rules: [
    {
      title: "Driver, unless there's a real reason not to.",
      body: 'A real reason is a pinch to 20 yards or a bunker you\'ll reach. "I hit my 5-iron straighter" is not a reason. You are not as accurate with it as you think.',
    },
    {
      title: 'Aggressive off the tee, conservative into the green.',
      body: 'Center of the green, never short-sided. Pin back right, hit center-left. You cannot be too conservative into a green.',
    },
    {
      title: 'Angles are worth almost nothing.',
      body: "The center of the fairway is worth a lot. Don't hug a hazard for a better look at the flag.",
    },
    {
      title: 'Blind is not dangerous.',
      body: 'Gorse, the beach and the thick stuff are. Get the line from the stone or the caddie, then commit.',
    },
    {
      title: 'Distance matters most over 450 yards.',
      body: "On 380 to 440 holes, 3-wood is fine if you love it. Don't lay way back and leave a long iron in.",
    },
    {
      title: 'Play the ground and the wind, not the stock number.',
      body: 'Firm adds 10 to 15 yards of run. Downwind, driver can go 350. Into it, get the ball on the ground early.',
    },
    {
      title: 'Scoring chances: 1, 12, 16.',
      body: 'Go for the par 5s in two after a good drive. Everywhere else, par is a win on a very hard golf course.',
    },
  ],
  holes: [
    {
      n: 1, par: 5, yards: 503, si: 13, tags: ['DRIVER', 'SCORING'], source: 'joe',
      offTheTee: 'Driver, center. Go in two.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: "Driver, dead center. The fairway bowls a little, so some people aim right-center and let the slope feed it back left. Joe would aim straight down the middle. Tee is beside the starter's hut." },
        { label: 'WATCH', joe: true, text: "Trouble is all down the right, along the beach. Give yourself a buffer on that side; the buffer is worth more than any angle into the green. Short of the green there's mounding and native grass. You probably won't lose a ball in it, but you don't want to be playing out of it." },
        { label: 'IN', joe: true, text: 'Good drive, go for it in two. Favor a hair left of the mounding short of the green.' },
        { label: 'NOTE', joe: true, text: 'Best scoring chance until 12. Old Tom Morris laid the course out in 1889; Combe, Vardon and then Harry Colt in the 1920s made it what it is.' },
      ],
    },
    {
      n: 2, par: 4, yards: 387, si: 9, tags: ['DRIVER / 3W', 'BLIND'], source: 'joe',
      offTheTee: 'Driver or 3W. Blind, left-center.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: 'Blind over the mound. Driver is not required at 387; 3-wood is a fine play if you like it. Distance only starts to matter a lot on holes over 450.' },
        { label: 'LINE', joe: true, text: 'A little right of the mound, to the left-center of the fairway. The mound is what makes it blind; the caddie sets the start line. Caddies may argue about which side. Joe says left-center and move on.' },
        { label: 'WATCH', joe: true, text: 'The right side is where you can get into trouble. The left half of the fairway is the safe half.' },
        { label: 'IN', joe: true, text: 'Nothing severe around the green. Center.' },
        { label: 'NOTE', joe: true, text: "First of the blind tee shots. Get the line, commit, don't overthink it." },
      ],
    },
    {
      n: 3, par: 4, yards: 455, si: 3, tags: ['DRIVER'], source: 'joe',
      offTheTee: 'Driver, center.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: "Driver, center. At 455 you need the distance. 3-wood only if you're comfortably carrying it 300." },
        { label: 'LINE', joe: true, text: 'Center of the fairway. Dunes on both sides.' },
        { label: 'WATCH', joe: true, text: "From the right side the approach can be blind because of the dunes. Joe doesn't care much about blindness; he cares about the thick stuff right and left, which costs far more than an obscured view." },
        { label: 'BUNKERS', text: '191 left, 224 right.' },
        { label: 'IN', joe: true, text: 'Center of the green. If the approach is blind, get the line from the caddie and hit it.' },
        { label: 'NOTE', text: "A lot of people call this the best hole on the course and Joe doesn't argue. Stroke index 3. Par is a great score." },
      ],
    },
    {
      n: 4, par: 3, yards: 202, si: 15, tags: ['ALL CARRY'], source: 'joe',
      offTheTee: 'All carry. Half a club less.', teeIsJoe: true,
      sections: [
        { label: 'CLUB', joe: true, text: "202, downhill, all carry. Take about half a club off and no more; it isn't dramatically downhill." },
        { label: 'LINE', joe: true, text: 'Middle of the green.' },
        { label: 'WATCH', text: 'Short is gorse and bunkers, and a ball in the gorse is not coming back. There is no running one up here.', joe: true },
        { label: 'BUNKERS', text: '145 to 181 short and left of the green, 155 to 172 right.' },
        { label: 'NOTE', joe: true, text: "One of the best holes on the course. There's no strategy on a 200-yard par 3: step up and hit a good one." },
      ],
    },
    {
      n: 5, par: 4, yards: 419, si: 7, tags: ['240 TO 250', 'BLIND'], source: 'joe',
      offTheTee: '240 to 250 at the white stone.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: 'Not driver. Hit something 240 to 250 over the big mound, leaving 170 to 175 in.' },
        { label: 'LINE', joe: true, text: "The white stone. It's the line for everybody regardless of length, even though the hole doglegs. Long hitters go a hair right of it. You're aiming a little left of a bunker you can't see from the tee." },
        { label: 'WATCH', joe: true, text: 'Past 250 the fairway pinches to about 18 yards. Firm turf or a helping wind and a 3-wood runs into it. Get a feel for the roll over the first four holes and club down again if it\'s fast.' },
        { label: 'BUNKERS', text: '240, 256 and 287 from the tee. 240 is your ceiling.' },
        { label: 'IN', joe: true, text: 'Center of the green.' },
        { label: 'NOTE', joe: true, text: 'Quirky and high on the blindness scale. Tee is just right of the 4th green. 419 is measured on the dogleg, not the beeline.' },
      ],
    },
    {
      n: 6, par: 4, yards: 355, si: 11, tags: ['DRIVER'], source: 'joe',
      offTheTee: 'Driver (iron OK). Tiny green.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: "Joe leans driver. It takes a big hit to reach the bunker and the fairway doesn't narrow much 30 yards farther up, so push it up. An iron off the tee is fine but leaves 135 to 140 into a tiny target. If your partner wants to hit something 220 to 230, don't talk him out of it." },
        { label: 'LINE', joe: true, text: 'Center.' },
        { label: 'WATCH', joe: true, text: 'Smallest green on the course, an upside-down saucer that falls off in every direction. The closer you are, the better.' },
        { label: 'IN', joe: true, text: 'Center of the green with the shortest club you can manage.' },
        { label: 'NOTE', joe: true, text: "355 yards. If you hate driver and love your 135-yard shot, playing it conservative here isn't a killer." },
      ],
    },
    {
      n: 7, par: 3, yards: 125, si: 17, tags: ['PRECISION'], source: 'joe',
      offTheTee: 'Center, hair right.', teeIsJoe: true,
      sections: [
        { label: 'CLUB', joe: true, text: '125 yards, a wedge or short iron. A precision hole, nothing else.' },
        { label: 'LINE', joe: true, text: 'Center of the green, maybe a hair right. Others say right-center; Joe says don\'t overdo it.' },
        { label: 'WATCH', joe: true, text: "The green slopes extremely hard to the left. Even a shot on the left half rolls off and down into the big, steep bunker. A lot of shots end up there. If yours does, it's the hole, not you." },
        { label: 'BUNKERS', text: '107 short, 129 and 148 left, 156 long.' },
        { label: 'NOTE', joe: true, text: 'Shortest hole on the course and one of the coolest. Hit it in the middle and get out with 3.' },
      ],
    },
    {
      n: 8, par: 4, yards: 414, si: 1, tags: ['DRIVER'], source: 'joe',
      offTheTee: 'Driver at the left bunker.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: "Driver down the center. No reason to hit less. The fairway narrows from about 38 yards to 30 or 31 at driver distance, but that's not lost-ball territory." },
        { label: 'LINE', joe: true, text: 'The bunker on the left in the distance, which Joe believes you can see from the tee, or a hair left of the green. The slight dogleg adds a little length.' },
        { label: 'WATCH', text: 'Stroke index 1. Par here wins holes.' },
        { label: 'BUNKERS', text: '204 left and 209 right at the landing area.' },
        { label: 'IN', joe: true, text: 'Center of the green.' },
        { label: 'NOTE', text: "A straightforward hole that's hard because it's long and the wind is usually doing something." },
      ],
    },
    {
      n: 9, par: 4, yards: 427, si: 5, tags: ['DRIVER', 'BLIND', 'PHOTO'], source: 'joe',
      offTheTee: 'Driver, right of the marker.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: 'Driver over the ridge. The tee shot is blind: an upper fairway, then a massive drop into the valley where your ball should land.' },
        { label: 'LINE', joe: true, text: 'A little right of the marker (a stone or small pole) on the first fairway. The caddie will point it out. Aim there and swing.' },
        { label: 'WATCH', joe: true, text: 'Nothing at the green you need to worry about. More scenic than strategic.' },
        { label: 'IN', joe: true, text: 'Once you\'re down in the valley the approach is flat. Center of the green.' },
        { label: 'NOTE', joe: true, text: 'One of the most famous holes in the world. Walk to the top of the ridge and take the photo looking down the fairway with the spire behind. Then a pause upstairs in the clubhouse before 10.' },
      ],
    },
    {
      n: 10, par: 3, yards: 180, si: 18, tags: ['CENTER'], source: 'joe',
      offTheTee: 'Center of the green.', teeIsJoe: true,
      sections: [
        { label: 'CLUB', joe: true, text: '180, fairly flat.' },
        { label: 'LINE', joe: true, text: 'Center of the green.' },
        { label: 'WATCH', joe: true, text: "Four bunkers around the green. Miss them and it's an easy par." },
        { label: 'BUNKERS', text: '155 and 156 front, 169 left, 181 back right.' },
        { label: 'NOTE', text: "Easiest hole by index. Cool green, nothing strategic. Don't hand back a shot here. The clubhouse crowd has a view of this tee." },
      ],
    },
    {
      n: 11, par: 4, yards: 430, si: 8, tags: ['DRIVER', 'BLIND'], source: 'joe',
      offTheTee: 'Driver at the stone.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: "Driver. As blind as tee shots get. At 430 there's no reason to hit less; 3-wood only if you truly can't hit driver." },
        { label: 'LINE', joe: true, text: 'The stone on the left side. It puts you on the left-center of the fairway, which is where you want to be.' },
        { label: 'WATCH', joe: true, text: 'More trouble down the right, with mounding and thick grass, than the left. The native area left is not a place to be either, so prioritize the center and trust the stone.' },
        { label: 'BUNKERS', text: '211 on the left.' },
        { label: 'IN', joe: true, text: 'Center of the green.' },
        { label: 'NOTE', joe: true, text: "Joe's test for hitting less than driver: the hole narrows to something like 20 yards, or there are bunkers you'd reach. Neither applies here." },
      ],
    },
    {
      n: 12, par: 5, yards: 469, si: 16, tags: ['DRIVER', 'SCORING'], source: 'joe',
      offTheTee: 'Driver, center. Go in two.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: 'Driver. Straight away and about 25 yards wide, with edges Joe remembers as playable rather than penal.' },
        { label: 'LINE', joe: true, text: 'Center.' },
        { label: 'WATCH', joe: true, text: "Bunkers in the layup zone if you aren't going for it. How thick the rough plays depends on the weather: dry and you can bash away, wet and it's more penal (and you get less roll anyway)." },
        { label: 'BUNKERS', text: '210 left, 221 right.' },
        { label: 'IN', joe: true, text: 'A 270 drive leaves about 200 and most of the group can get there. Go for it. The green gets quick depending on where you miss; center.' },
        { label: 'NOTE', joe: true, text: 'Second par 5 and the last real scoring chance. Cool green.' },
      ],
    },
    {
      n: 13, par: 4, yards: 423, si: 2, tags: ['DRIVER / 3W'], source: 'joe',
      offTheTee: 'Driver or 3W, center.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: 'Driver or 3-wood, nothing shorter. The fairway is 26 to 28 yards wide at 3-wood distance and 24 to 25 at driver. Joe is fine with driver and doesn\'t want anyone laying way back and leaving a long iron in.' },
        { label: 'LINE', joe: true, text: 'Center. People will tell you the left side gives a cleaner look at the green. Slightly better angle, not worth the risk.' },
        { label: 'WATCH', joe: true, text: 'Stroke index 2. The green sits in a bowl of gorse.' },
        { label: 'BUNKERS', text: '228 and 264 up the right side.' },
        { label: 'IN', joe: true, text: "The green is tricky, but don't change strategy because of it. Center, no hero shots." },
        { label: 'NOTE', joe: true, text: 'Look for the staircase by the green, one of the most serene spots on the course. End of what Joe calls the really special stretch, 1 through 13.' },
      ],
    },
    {
      n: 14, par: 3, yards: 202, si: 12, tags: ['CENTER'], source: 'joe',
      offTheTee: 'Middle of the green.', teeIsJoe: true,
      sections: [
        { label: 'CLUB', joe: true, text: 'A full 200-yard shot. Tee box is back by the path.' },
        { label: 'LINE', joe: true, text: 'Middle of the green.' },
        { label: 'WATCH', joe: true, text: 'Severe bunkering all around the green.' },
        { label: 'BUNKERS', text: '170 and 173 front, 185 right, 188 left.' },
        { label: 'NOTE', joe: true, text: 'Nothing to do but step up and hit a good one. Long par 3s here are about commitment, not strategy.' },
      ],
    },
    {
      n: 15, par: 4, yards: 420, si: 4, tags: ['DRIVER'], source: 'joe',
      offTheTee: 'Driver, center (uphill).', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: "Driver. The drive is uphill and the dogleg adds length, so it plays longer than the card. The fairway pinches around 265 to 270 but the grass there isn't that dangerous." },
        { label: 'LINE', joe: true, text: "Center of the fairway. If it runs through into the rough at the pinch, that's fine." },
        { label: 'WATCH', joe: true, text: "A mis-hit 3-wood leaves 205 in. That's the risk in clubbing down. Only the longest hitters should consider 3-wood, and even then ask the caddie." },
        { label: 'IN', joe: true, text: 'Center of the green.' },
        { label: 'NOTE', joe: true, text: 'A cool hole; some people extend the great stretch to 15 because of it.' },
      ],
    },
    {
      n: 16, par: 4, yards: 300, si: 14, tags: ['DRIVABLE', 'SCORING'], source: 'joe',
      offTheTee: 'Driver, or 220 to 230 left.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: 'Two plays. Accurate driver who can hit it 280 to 290: hit driver and bounce it up to the front-left edge of the green. Otherwise hit something 220 to 230 down the left and leave a flip wedge.' },
        { label: 'LINE', joe: true, text: 'Left side either way.' },
        { label: 'WATCH', joe: true, text: 'It looks narrower than it is, but the drive carries real risk, which is what makes the risk-reward good. Half the group laying up and half sending it is normal. This is not a no-brainer send.' },
        { label: 'BUNKERS', text: '264 right, 287 left. The layup stops short of both.' },
        { label: 'IN', text: 'Wedge to the middle of the green.' },
        { label: 'NOTE', joe: true, text: "Drivable, stroke index 14. Joe leans aggressive on drivable par 4s. If you're comfortable with the drive, hit it." },
      ],
    },
    {
      n: 17, par: 4, yards: 402, si: 10, tags: ['DRIVER', '3W IF LONG'], source: 'joe',
      offTheTee: 'Driver. 3W if long and firm.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: "Driver for most of the group. If you're long and it's firm or downwind, 3-wood short of the sand scrape." },
        { label: 'LINE', joe: true, text: "Center. There's no room to go left or right of the scrape; the choice is over it or short of it." },
        { label: 'WATCH', joe: true, text: "The sand scrape in the middle of the hole is not water. It's a big blowout bunker with vegetation in it, and it replaced a water hazard about 15 years ago. Going in costs about a third of a shot, not a penalty, but it's an awkward hazard." },
        { label: 'BUNKERS', text: '227 right. Sand scrape starts at 272.' },
        { label: 'IN', joe: true, text: 'About 135 to 140 in to an okay green. Center.' },
        { label: 'NOTE', joe: true, text: '17 and 18 are fine holes, not the equal of the rest. Stay out of the scrape and take your par.' },
      ],
    },
    {
      n: 18, par: 5, yards: 528, si: 6, tags: ['DRIVER'], source: 'joe',
      offTheTee: 'Driver, center. Go in two.', teeIsJoe: true,
      sections: [
        { label: 'TEE', joe: true, text: "Driver. It's narrow, about 20 yards, with a lot of bunkers, and Joe still says driver. 3-wood leaves you a really long way in, isn't appreciably more accurate, and takes away the chance to go for it in two." },
        { label: 'LINE', joe: true, text: 'Center. Depending on the wind, the longer hitters may carry most of the bunkering.' },
        { label: 'WATCH', joe: true, text: "Bunkers, not rough; Joe doesn't remember the grass being thick here. The course down the right is the Annesley, the members' winter links." },
        { label: 'BUNKERS', text: '195 and 217 left, 213 and 234 right.' },
        { label: 'IN', joe: true, text: 'Good drive, go for it in two. Super narrow, and worth it.' },
        { label: 'NOTE', text: 'Par 5, stroke index 6. Finish with something aggressive.' },
      ],
    },
  ],
  quickLook: [
    { title: 'Blind tee shots: 2, 5, 9, 11', joe: true, body: '2 over the mound, left-center. 5 at the white stone. 9 over the ridge, right of the marker. 11 at the stone, left-center. The approach on 3 can be blind from the right.' },
    { title: 'Scoring chances: 1, 12, 16', joe: true, body: 'Two reachable par 5s and a drivable par 4. Everything else, take par and walk.' },
    { title: "Club down off the tee: 5, and 17 if you're long", joe: true, body: '5 is 240 to 250, never driver. 17 is 3-wood only if you can reach the sand scrape (firm or downwind).' },
    { title: "Don't be short: 4 and 7", joe: true, body: '4 is all carry over gorse. 7 feeds everything left into the deep bunker; aim center, a hair right.' },
    { title: 'Toughest by index: 8, 13, 3, 15', body: 'Par on any of these is a point won. No hero shots on 8 or 13.' },
    { title: 'Where it narrows: 5, 13, 18', joe: true, body: '5 pinches to 18 yards past 250. 13 is 24 to 25 yards at driver. 18 is about 20 yards. Joe still says driver on 13 and 18.' },
    { title: 'Photo: 9', joe: true, body: 'From the top of the ridge, looking down at the fairway with the spire behind. Then a pint upstairs between 9 and 10.' },
  ],
  closing: ['Center of the fairway.', 'Center of the green.', 'Hit driver.'],
  closingSub: 'Angles are worth nothing. Your ball is worth a lot.',
};
